-- MySQL Script generated by MySQL Workbench
-- Tue Nov 18 09:07:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LatinNowDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LatinNowDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LatinNowDB` DEFAULT CHARACTER SET utf8 ;
USE `LatinNowDB` ;

-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_place_assoc_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_place_assoc_type` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_place_assoc_type` (
  `id_code` INT NULL DEFAULT NULL,
  `category` VARCHAR(1) NOT NULL,
  `connection` VARCHAR(1) NOT NULL,
  `name` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_inscrobj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_inscrobj` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_inscrobj` (
  `id_code` INT NULL DEFAULT NULL,
  `modified_datetime_iso` VARCHAR(25) NOT NULL,
  `modified_user` VARCHAR(15) NOT NULL,
  `status` INT NOT NULL,
  `notes_internal` TEXT NOT NULL,
  `date_range_start` INT NOT NULL,
  `date_range_start_cert` INT NOT NULL,
  `date_range_end` INT NOT NULL,
  `date_range_end_cert` INT NOT NULL,
  `geo_coordinates` VARCHAR(31) NOT NULL,
  `language` VARCHAR(79) NOT NULL,
  `material` VARCHAR(79) NOT NULL,
  `object_type` VARCHAR(63) NOT NULL,
  `place_name` VARCHAR(63) NOT NULL,
  `province` VARCHAR(47) NOT NULL,
  `text_type` VARCHAR(79) NOT NULL,
  `geo_coordinate_source` INT NOT NULL,
  `date_authority_id` INT NOT NULL,
  `script` VARCHAR(63) NOT NULL,
  `notes_external` TEXT NOT NULL,
  `text_source_id` INT NOT NULL,
  `region` VARCHAR(255) NOT NULL,
  `multilingualism` VARCHAR(255) NOT NULL,
  `geo_assoc_type_id` INT NOT NULL,
  `geo_assoc_place_id` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`geo_assoc_type_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`geo_assoc_type_id`)
    REFERENCES `LatinNowDB`.`latnow_place_assoc_type` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_source` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_source` (
  `fileName` VARCHAR(47) NULL DEFAULT NULL,
  `x_publAuth` VARCHAR(79) NULL DEFAULT NULL,
  `x_localID` VARCHAR(23) NULL DEFAULT NULL,
  `x_tmID` VARCHAR(79) NULL DEFAULT NULL,
  `x_cilID` VARCHAR(79) NULL DEFAULT NULL,
  `x_edhID` VARCHAR(159) NULL DEFAULT NULL,
  `x_petraeID` VARCHAR(63) NULL DEFAULT NULL,
  `x_uri` VARCHAR(79) NULL DEFAULT NULL,
  `x_modernPlaceName` VARCHAR(79) NULL DEFAULT NULL,
  `x_modernPlaceNameGeo` VARCHAR(79) NULL DEFAULT NULL,
  `x_modernRegion` VARCHAR(79) NULL DEFAULT NULL,
  `x_modernRegionRef` VARCHAR(79) NULL DEFAULT NULL,
  `x_inscrip_type` VARCHAR(79) NULL DEFAULT NULL,
  `x_civitas` VARCHAR(31) NULL DEFAULT NULL,
  `x_material` VARCHAR(159) NULL DEFAULT NULL,
  `x_origPlaceName` VARCHAR(79) NULL DEFAULT NULL,
  `x_origPlaceNameRef` VARCHAR(79) NULL DEFAULT NULL,
  `bibl` TEXT NULL DEFAULT NULL,
  `x_date_inscrip` VARCHAR(63) NULL DEFAULT NULL,
  `x_foundPlace` VARCHAR(159) NULL DEFAULT NULL,
  `x_foundPlaceRef` VARCHAR(79) NULL DEFAULT NULL,
  `x_foundPlaceModReg` VARCHAR(79) NULL DEFAULT NULL,
  `x_foundPlaceModRegRef` VARCHAR(79) NULL DEFAULT NULL,
  `x_foundPlaceModCountry` VARCHAR(79) NULL DEFAULT NULL,
  `x_foundPlaceModCountryRef` VARCHAR(79) NULL DEFAULT NULL,
  `x_inscrip_lang` VARCHAR(31) NULL DEFAULT NULL,
  `x_province` VARCHAR(31) NOT NULL,
  `text_markup` TEXT NOT NULL,
  `notes` TEXT NOT NULL,
  `id_code` INT NOT NULL,
  `x_foundPlaceModCountryID` INT NOT NULL,
  `x_foundPlaceModRegionID` INT NOT NULL,
  `x_foundPlaceID` INT NOT NULL,
  `x_origPlaceID` INT NOT NULL,
  `x_modernRegionID` INT NOT NULL,
  `x_modernPlaceID` INT NOT NULL,
  `x_materialID` INT NOT NULL,
  `x_provinceID` INT NOT NULL,
  `x_publAuthID` INT NOT NULL,
  `x_civitas_id` INT NOT NULL,
  `x_inscrip_type_id` INT NOT NULL,
  `geo_coords_calc` VARCHAR(31) NOT NULL,
  `x_hispEpID` VARCHAR(7) NOT NULL,
  `x_objectType` VARCHAR(63) NOT NULL,
  `x_objectTypeRef` VARCHAR(79) NOT NULL,
  `modified_datetime_iso` VARCHAR(25) NOT NULL,
  `date_range_start` INT NOT NULL,
  `date_range_start_cert` INT NOT NULL,
  `date_range_end` INT NOT NULL,
  `date_range_end_cert` INT NOT NULL,
  `dupe_checked` TINYINT NOT NULL,
  `dupe_checked_by` VARCHAR(15) NOT NULL,
  `dupe_checked_date` DATE NOT NULL,
  `province` VARCHAR(31) NOT NULL,
  `material` VARCHAR(79) NOT NULL,
  `objectType_EAGLE` VARCHAR(63) NOT NULL,
  `language` VARCHAR(79) NOT NULL,
  `modified_user` VARCHAR(15) NOT NULL,
  `text_canonical` TEXT NOT NULL,
  `text_similar_ids` TEXT NOT NULL,
  `text_similar_compared_datetime` VARCHAR(25) NOT NULL,
  `x_textType` VARCHAR(63) NOT NULL,
  `x_textTypeRef` VARCHAR(79) NOT NULL,
  `text_type` VARCHAR(79) NOT NULL,
  `is_deprecated` TINYINT NOT NULL,
  `x_edcs_place` VARCHAR(80) NOT NULL,
  `x_edcs_province` VARCHAR(31) NOT NULL,
  `x_edcs_date` VARCHAR(79) NOT NULL,
  `x_edcs_genus_pers_status` VARCHAR(143) NOT NULL,
  `x_edcs_material` VARCHAR(15) NOT NULL,
  `x_edcs_commentary` VARCHAR(127) NOT NULL,
  `x_edcs_bibliography` TEXT NOT NULL,
  `x_edcs_text` TEXT NOT NULL,
  `date_source_id` INT NOT NULL,
  `place_name_calc` VARCHAR(63) NOT NULL,
  `is_unique` TINYINT NOT NULL,
  `text_identical_count` INT NOT NULL,
  `text_similar_count` INT NOT NULL,
  `inscrobj_parent_id` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`inscrobj_parent_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`inscrobj_parent_id`)
    REFERENCES `LatinNowDB`.`latnow_inscrobj` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_place_zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_place_zone` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_place_zone` (
  `id_code` INT NULL DEFAULT NULL,
  `zone_name` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  UNIQUE INDEX (`zone_name` ASC) VISIBLE,
  PRIMARY KEY (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_place` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_place` (
  `id_code` INT NULL DEFAULT NULL,
  `place_name` VARCHAR(79) NOT NULL,
  `place_type_usage` VARCHAR(15) NOT NULL,
  `place_geo` VARCHAR(31) NOT NULL,
  `place_ref_pleiades` VARCHAR(47) NOT NULL,
  `place_ref_tm` VARCHAR(47) NOT NULL,
  `notes` TEXT NOT NULL,
  `place_ref_geonames` VARCHAR(63) NOT NULL,
  `parent_region` VARCHAR(31) NOT NULL,
  `geo_source` VARCHAR(1) NOT NULL,
  `related_inscription_total` INT NOT NULL,
  `place_ref_edh` VARCHAR(9) NOT NULL,
  `place_ref_wikidata` VARCHAR(15) NOT NULL,
  `is_provisional` TINYINT NOT NULL,
  `place_name_sort` VARCHAR(79) NOT NULL,
  `modified_datetime_iso` VARCHAR(25) NOT NULL,
  `modified_user` VARCHAR(15) NOT NULL,
  `province_id` INT NOT NULL,
  `parent_region_id` INT NOT NULL,
  `shape_code` VARCHAR(1) NOT NULL,
  `zone_id` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`zone_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`zone_id`)
    REFERENCES `LatinNowDB`.`latnow_place_zone` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_attribute_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_attribute_type` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_attribute_type` (
  `id_code` INT NULL DEFAULT NULL,
  `name` VARCHAR(63) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_attribute` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_attribute` (
  `id_code` INT NULL DEFAULT NULL,
  `name_full` VARCHAR(255) NOT NULL,
  `type_id` INT NOT NULL,
  `name_short` VARCHAR(47) NOT NULL,
  `name_sort` VARCHAR(255) NOT NULL,
  `attr_ref` VARCHAR(255) NOT NULL,
  `modified_datetime_iso` VARCHAR(25) NOT NULL,
  `is_deprecated` TINYINT NOT NULL,
  `rib_taxonomy_id` INT NOT NULL,
  `related_count` INT NOT NULL,
  `notes` TEXT NOT NULL,
  `modified_user` VARCHAR(255) NOT NULL,
  `uri_pattern` VARCHAR(127) NOT NULL,
  `parent_id` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`type_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`type_id`)
    REFERENCES `LatinNowDB`.`latnow_attribute_type` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_certainty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_certainty` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_certainty` (
  `id_code` INT NULL DEFAULT NULL,
  `name` VARCHAR(31) NOT NULL,
  `template` VARCHAR(79) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_source_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_source_attribute` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_source_attribute` (
  `id_code` INT NULL DEFAULT NULL,
  `attribute_id` INT NOT NULL,
  `inscription_id` INT NOT NULL,
  `certainty_id` INT NOT NULL,
  `source_publ_auth_id` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`inscription_id` ASC) VISIBLE,
  INDEX (`attribute_id` ASC) VISIBLE,
  INDEX (`certainty_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`inscription_id`)
    REFERENCES `LatinNowDB`.`latnow_source` (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`attribute_id`)
    REFERENCES `LatinNowDB`.`latnow_attribute` (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`certainty_id`)
    REFERENCES `LatinNowDB`.`latnow_certainty` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_source_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_source_place` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_source_place` (
  `id_code` INT NULL DEFAULT NULL,
  `place_id` INT NOT NULL,
  `inscription_id` INT NOT NULL,
  `connection` VARCHAR(1) NOT NULL,
  `certainty_id` INT NOT NULL,
  `category` VARCHAR(1) NOT NULL,
  `source_publ_auth_id` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`inscription_id` ASC) VISIBLE,
  INDEX (`place_id` ASC) VISIBLE,
  INDEX (`certainty_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`inscription_id`)
    REFERENCES `LatinNowDB`.`latnow_source` (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`place_id`)
    REFERENCES `LatinNowDB`.`latnow_place` (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`certainty_id`)
    REFERENCES `LatinNowDB`.`latnow_certainty` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_source_rel_identifier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_source_rel_identifier` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_source_rel_identifier` (
  `id_code` INT NULL DEFAULT NULL,
  `inscription_id` INT NOT NULL,
  `identifier_type_id` INT NOT NULL,
  `identifier_value` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`inscription_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`inscription_id`)
    REFERENCES `LatinNowDB`.`latnow_source` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_source_identity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_source_identity` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_source_identity` (
  `id_code` INT NULL DEFAULT NULL,
  `merge_id` INT NOT NULL,
  `original_id` INT NOT NULL,
  `is_provisional` TINYINT NOT NULL,
  `is_merged` TINYINT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`merge_id` ASC) VISIBLE,
  INDEX (`original_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`merge_id`)
    REFERENCES `LatinNowDB`.`latnow_source` (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`original_id`)
    REFERENCES `LatinNowDB`.`latnow_source` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`inscrip_taxonomy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`inscrip_taxonomy` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`inscrip_taxonomy` (
  `id_code` INT NULL DEFAULT NULL,
  `xml_id` VARCHAR(79) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `parent_taxonomy_id` VARCHAR(31) NOT NULL,
  `parent_id` INT NOT NULL,
  `eagle_uri` VARCHAR(127) NOT NULL,
  `sort_order` INT NOT NULL,
  `notes` TEXT NOT NULL,
  `old_id` INT NOT NULL,
  `latnow_attr_id` INT NOT NULL,
  `fair_epigraphy_uri` VARCHAR(127) NOT NULL,
  `is_deprecated` TINYINT NOT NULL,
  `wikidata_id` VARCHAR(15) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  UNIQUE INDEX (`xml_id` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`latnow_attr_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`latnow_attr_id`)
    REFERENCES `LatinNowDB`.`latnow_attribute` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_source_bibl_ref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_source_bibl_ref` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_source_bibl_ref` (
  `id_code` INT NULL DEFAULT NULL,
  `inscription_id` INT NOT NULL,
  `ref_original` TEXT NOT NULL,
  `ref_normalized` VARCHAR(63) NOT NULL,
  `sort_order` INT NOT NULL,
  `ref_type` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`inscription_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`inscription_id`)
    REFERENCES `LatinNowDB`.`latnow_source` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_source_queue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_source_queue` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_source_queue` (
  `id_code` INT NULL DEFAULT NULL,
  `inscription_id` INT NOT NULL,
  `status` INT NOT NULL,
  `enqueued_datetime` VARCHAR(25) NOT NULL,
  `priority` INT NOT NULL,
  `enqueued_by_user_id` INT NOT NULL,
  `started_datetime` VARCHAR(25) NOT NULL,
  `completed_datetime` VARCHAR(25) NOT NULL,
  `time_seconds` INT NOT NULL,
  `notify_user` TINYINT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`inscription_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`inscription_id`)
    REFERENCES `LatinNowDB`.`latnow_source` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_setting` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_setting` (
  `id_code` INT NULL DEFAULT NULL,
  `setting_name` VARCHAR(79) NOT NULL,
  `value_text` VARCHAR(255) NOT NULL,
  `value_longint` INT NOT NULL,
  `value_boolean` TINYINT NOT NULL,
  `value_type` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_name_variant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_name_variant` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_name_variant` (
  `id_code` INT NULL DEFAULT NULL,
  `name` VARCHAR(79) NOT NULL,
  `variant_type` INT NOT NULL,
  `parent_table_id` INT NOT NULL,
  `parent_id` INT NOT NULL,
  `certainty_id` INT NOT NULL,
  `language_attribute_id` INT NOT NULL,
  `related_entity_id` INT NOT NULL,
  `notes` TEXT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`certainty_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`certainty_id`)
    REFERENCES `LatinNowDB`.`latnow_certainty` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_source_similarity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_source_similarity` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_source_similarity` (
  `id_code` INT NULL DEFAULT NULL,
  `inscription_id` INT NOT NULL,
  `similar_id_list` TEXT NOT NULL,
  `identical_id_list` TEXT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`inscription_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`inscription_id`)
    REFERENCES `LatinNowDB`.`latnow_source` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_inscrobj_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_inscrobj_attribute` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_inscrobj_attribute` (
  `id_code` INT NULL DEFAULT NULL,
  `attribute_id` INT NOT NULL,
  `inscrobj_id` INT NOT NULL,
  `certainty_id` INT NOT NULL,
  `source_publ_auth_id` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`certainty_id` ASC) VISIBLE,
  INDEX (`inscrobj_id` ASC) VISIBLE,
  INDEX (`attribute_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`certainty_id`)
    REFERENCES `LatinNowDB`.`latnow_certainty` (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`inscrobj_id`)
    REFERENCES `LatinNowDB`.`latnow_inscrobj` (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`attribute_id`)
    REFERENCES `LatinNowDB`.`latnow_attribute` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_inscrobj_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_inscrobj_place` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_inscrobj_place` (
  `id_code` INT NULL DEFAULT NULL,
  `place_id` INT NOT NULL,
  `inscrobj_id` INT NOT NULL,
  `connection` VARCHAR(1) NOT NULL,
  `certainty_id` INT NOT NULL,
  `category` VARCHAR(1) NOT NULL,
  `source_publ_auth_id` INT NOT NULL,
  `status` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`place_id` ASC) VISIBLE,
  INDEX (`inscrobj_id` ASC) VISIBLE,
  INDEX (`certainty_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`place_id`)
    REFERENCES `LatinNowDB`.`latnow_place` (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`inscrobj_id`)
    REFERENCES `LatinNowDB`.`latnow_inscrobj` (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`certainty_id`)
    REFERENCES `LatinNowDB`.`latnow_certainty` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_inscrobj_rel_identifier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_inscrobj_rel_identifier` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_inscrobj_rel_identifier` (
  `id_code` INT NULL DEFAULT NULL,
  `inscrobj_id` INT NOT NULL,
  `identifier_type_id` INT NOT NULL,
  `identifier_value` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`inscrobj_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`inscrobj_id`)
    REFERENCES `LatinNowDB`.`latnow_inscrobj` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_inscrobj_bibl_ref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_inscrobj_bibl_ref` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_inscrobj_bibl_ref` (
  `id_code` INT NULL DEFAULT NULL,
  `inscrobj_id` INT NOT NULL,
  `ref_original` TEXT NOT NULL,
  `ref_normalized` VARCHAR(63) NOT NULL,
  `sort_order` INT NOT NULL,
  `ref_type` INT NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  INDEX (`inscrobj_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`inscrobj_id`)
    REFERENCES `LatinNowDB`.`latnow_inscrobj` (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_bibl_ref_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_bibl_ref_type` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_bibl_ref_type` (
  `id_code` INT NULL DEFAULT NULL,
  `type_name` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  UNIQUE INDEX (`type_name` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`id_code`)
    REFERENCES `LatinNowDB`.`latnow_inscrobj_bibl_ref` (`ref_type`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_place_geo_source_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_place_geo_source_type` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_place_geo_source_type` (
  `id_code` INT NULL DEFAULT NULL,
  `type_code` VARCHAR(1) NOT NULL,
  `type_name` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  UNIQUE INDEX (`type_code` ASC) VISIBLE,
  UNIQUE INDEX (`type_name` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`type_code`)
    REFERENCES `LatinNowDB`.`latnow_place` (`geo_source`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_place_shape_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_place_shape_code` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_place_shape_code` (
  `id_code` INT NULL DEFAULT NULL,
  `type_code` VARCHAR(1) NOT NULL,
  `shape_name` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  UNIQUE INDEX (`type_code` ASC) VISIBLE,
  UNIQUE INDEX (`shape_name` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`type_code`)
    REFERENCES `LatinNowDB`.`latnow_place` (`shape_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_place_usage_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_place_usage_code` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_place_usage_code` (
  `id_code` INT NULL DEFAULT NULL,
  `usage_code` VARCHAR(1) NOT NULL,
  `usage_name` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  UNIQUE INDEX (`usage_code` ASC) VISIBLE,
  UNIQUE INDEX (`usage_name` ASC) VISIBLE,
  PRIMARY KEY (`id_code`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_name_variant_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_name_variant_type` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_name_variant_type` (
  `id_code` INT NULL DEFAULT NULL,
  `variant_name` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  UNIQUE INDEX (`variant_name` ASC) VISIBLE,
  PRIMARY KEY (`id_code`),
  CONSTRAINT ``
    FOREIGN KEY (`id_code`)
    REFERENCES `LatinNowDB`.`latnow_name_variant` (`variant_type`));


-- -----------------------------------------------------
-- Table `LatinNowDB`.`latnow_record_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LatinNowDB`.`latnow_record_status` ;

CREATE TABLE IF NOT EXISTS `LatinNowDB`.`latnow_record_status` (
  `id_code` INT NULL DEFAULT NULL,
  `status_name` VARCHAR(31) NOT NULL,
  UNIQUE INDEX (`id_code` ASC) VISIBLE,
  UNIQUE INDEX (`status_name` ASC) VISIBLE,
  PRIMARY KEY (`id_code`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
